name: Flaky Test Pipeline

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      should_fail:
        description: 'Fail the pipeline'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  flaky-test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 10 seconds
        run: sleep 10
      - name: Check should_fail
        run: |
          echo "Pipeline succeeded!"
